name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - exarch-core (Rust library)
        - exarch-python (Python bindings)
        - exarch-node (Node.js bindings)
        - exarch-cli (Command-line tool)
        - New format support
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        I'm trying to do X, but currently I have to Y, which is inconvenient because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API (optional)
      description: If applicable, show what the API might look like
      render: rust
      placeholder: |
        // Rust
        let config = SecurityConfig::default()
            .with_new_option(value);

        // Python
        config = exarch.SecurityConfig().new_option(value)

        // Node.js
        const config = new SecurityConfig().newOption(value);

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Blocking my use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute?
      options:
        - label: I would be willing to submit a PR for this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
