#!/usr/bin/env bash
# Assembles fuzz/seeds/<target>/ from three sources: existing repo fixtures,
# the adversarial archives generated by exarch-core's test_utils, and a
# handful of hand-written safe_path traversal strings. fuzz/seeds/ is
# gitignored and generated-only -- this script is the sole assembler, so
# fixture bytes live in git exactly once (see fuzz/README.md).
set -euo pipefail
# nullglob: a pattern with no matches (e.g. tests/fixtures/fuzz/<target>/*.bin
# before any crash has been minimized into that dir) expands to nothing
# instead of the literal pattern, which would otherwise fail under `set -e`.
shopt -s nullglob

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SEEDS="$REPO_ROOT/fuzz/seeds"
CORPUS="$REPO_ROOT/fuzz/corpus"

for target in tar zip sevenz safe_path extract_archive; do
  mkdir -p "$SEEDS/$target"
  # cargo-fuzz requires an explicitly-passed corpus dir to already exist; it
  # only auto-creates the default (no-arg) path. Without this, every matrix
  # leg in the scheduled `fuzz` job hard-fails with "required directory ...
  # does not exist" whenever the corpus cache is empty or evicted.
  mkdir -p "$CORPUS/$target"
done

# Fails loud on a name collision rather than silently overwriting an
# already-placed seed -- the exact bug class that motivated the tar-/zip-
# prefixing below and the crash-fixtures-run-last ordering further down.
copy_seed() {
  local src="$1" target="$2"
  local dest="$SEEDS/$target/$(basename "$src")"
  if [[ -e "$dest" ]]; then
    echo "seed-corpus.sh: refusing to overwrite existing seed $dest (from $src)" >&2
    exit 1
  fi
  cp "$src" "$dest"
}

# (a) Copy existing binary fixtures already committed to the repo.
for f in "$REPO_ROOT"/tests/fixtures/*.7z; do
  copy_seed "$f" sevenz
  copy_seed "$f" extract_archive
done

for f in "$REPO_ROOT"/tests/fixtures/zip-family/*.{jar,whl,apk,epub,vsix}; do
  copy_seed "$f" zip
  copy_seed "$f" extract_archive
done
if [[ -f "$REPO_ROOT/crates/exarch-cli/tests/fixtures/symlink.zip" ]]; then
  copy_seed "$REPO_ROOT/crates/exarch-cli/tests/fixtures/symlink.zip" zip
  copy_seed "$REPO_ROOT/crates/exarch-cli/tests/fixtures/symlink.zip" extract_archive
fi

for name in cve-2025-48387-hardlink.tar cve-2024-12905-symlink-escape.tar; do
  f="$REPO_ROOT/crates/exarch-python/tests/fixtures/$name"
  if [[ -f "$f" ]]; then
    copy_seed "$f" tar
    copy_seed "$f" extract_archive
  fi
done

# Compressed fixtures: extract_archive only -- the `tar` target parses
# uncompressed TAR exclusively.
if [[ -f "$REPO_ROOT/crates/exarch-python/tests/fixtures/cve-2025-4517-traversal.tar.gz" ]]; then
  copy_seed "$REPO_ROOT/crates/exarch-python/tests/fixtures/cve-2025-4517-traversal.tar.gz" extract_archive
fi
if [[ -f "$REPO_ROOT/crates/exarch-cli/tests/fixtures/sample.tar.gz" ]]; then
  copy_seed "$REPO_ROOT/crates/exarch-cli/tests/fixtures/sample.tar.gz" extract_archive
fi

# (b) Dump the programmatically-generated adversarial archives that only
# exist as pub(crate) generators in exarch-core's test_utils.
(cd "$REPO_ROOT" && cargo test -p exarch-core --lib -- --ignored dump_fuzz_seeds)

# The dump writes directly into seeds/tar and seeds/zip; also seed
# extract_archive with the same valid archives (detectable by magic bytes).
# Prefixed with the source target: tar/basic.bin and zip/basic.bin would
# otherwise collide on the same extract_archive/basic.bin filename.
for src in tar zip; do
  for f in "$SEEDS/$src"/*.bin; do
    cp "$f" "$SEEDS/extract_archive/${src}-$(basename "$f")"
  done
done

# Minimized crash reproducers committed per the crash-to-regression-test
# workflow (fuzz/README.md). Convention: tests/fixtures/fuzz/<target>/<slug>.bin.
# This directory normally does not exist until the first crash is minimized --
# nullglob above keeps that the no-op it should be. Run LAST, after (b)'s
# dump: a committed regression seed must always win a basename collision
# against a generated one, and copy_seed()'s fail-loud check enforces that a
# collision is never resolved silently either way -- it errors instead, so a
# clashing slug must be renamed rather than accidentally dropping a seed.
for target in tar zip sevenz safe_path extract_archive; do
  for f in "$REPO_ROOT"/crates/exarch-core/tests/fixtures/fuzz/"$target"/*.bin; do
    copy_seed "$f" "$target"
  done
done

# (c) Hand-written safe_path traversal / edge-case seeds. safe_path takes
# raw bytes as an entry name, not an archive, so these are plain text.
write_text_seed() {
  local name="$1" content="$2"
  printf '%s' "$content" >"$SEEDS/safe_path/$name"
}

write_text_seed parent-traversal.txt '../etc/passwd'
write_text_seed windows-traversal.txt '..\..\windows'
write_text_seed absolute-path.txt '/abs/path'
printf 'a\0b' >"$SEEDS/safe_path/embedded-nul.txt"
write_text_seed deep-nesting.txt "$(printf 'a/%.0s' {1..64})a"
write_text_seed overlong-component.txt "$(printf 'a%.0s' {1..300})"
printf '\xff\xfe/\x80\x81' >"$SEEDS/safe_path/non-utf8.txt"
write_text_seed dotdot-slash-slash.txt '....//....//etc/passwd'

echo "Seed corpus assembled under $SEEDS"
